make_weathertest : weather_text mid-term-rss3.jsp?stnId=108
	./weather_text mid-term-rss3.jsp?stnId=108

mid-term-rss3.jsp?stnId=108 :
	wget http://www.kma.go.kr/weather/forecast/mid-term-rss3.jsp?stnId=108
